// Данко Системс — начални контакти (157). Зареждат се еднократно в облака.
window.DANKO_CONTACTS = [
{
"category": "Доставчик – опаковки",
"company": "Хара ООД",
"contact_person": "Никола Тунев",
"phone": "877/713496",
"email": "",
"scope": "стреч, тиксо",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "взимаме от тях материали, заявката е по телефона"
},
{
"category": "Доставчик – опаковки",
"company": "Мава Индустриал АД",
"contact_person": "Пламен Славов",
"phone": "8882/68515",
"email": "plamen.slavov@mavaindustrial.com",
"scope": "стреч, тиксо",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "не сме взимали, имаме само оферти"
},
{
"category": "Доставчик – опаковки",
"company": "Бетелгиус ЕООД",
"contact_person": "Кирил Деликирев",
"phone": "893/637191",
"email": "fromm@betelgeus.com",
"scope": "стреч, тиксо",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "не сме взимали, имаме само оферти"
},
{
"category": "Доставчик – опаковки",
"company": "Кинтрейд ЕООД",
"contact_person": "",
"phone": "",
"email": "",
"scope": "пенополиетиленово фолио 2 мм",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Иван взима (Цариградско шосе); за Тип Тое опаковка"
},
{
"category": "Доставчик – опаковки",
"company": "Анталис България ЕООД",
"contact_person": "Моника Стаменова",
"phone": "896693319",
"email": "monika.stamenova@antalis.com",
"scope": "Пуканка за машина Mini park; NOVUS Supertube ST 480 4000mm x 150mm x 250mm",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Доставчик – опаковки",
"company": "Легно ЕООД",
"contact_person": "Антон Заимов",
"phone": "898/667 590",
"email": "a.zaimov@legnopacking.com",
"scope": "стреч",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "взимали сме от тях, но вече държат поръчката да е над 1000 лв"
},
{
"category": "Доставчик – кашони",
"company": "КАМ 919 ООД",
"contact_person": "Елена Мандурова",
"phone": "888/351503; 32/690727",
"email": "office@kam919.com",
"scope": "кашони",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "взимаме от тях кутии марко, кашон 3"
},
{
"category": "Доставчик – кашони",
"company": "ДС Смит",
"contact_person": "Димитър Враменцалиев",
"phone": "897/988109",
"email": "dimitar.vramentsaliev@dssmith.com",
"scope": "кашони",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "взимаме от тях кашони 1,2,4, за кашон 3 нямаме оферта, трябва да им предоставим мостра;"
},
{
"category": "Доставчик – кашони",
"company": "Мажор ЕООД",
"contact_person": "Любомир Ангелов",
"phone": "",
"email": "",
"scope": "кутии",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Стефан ги поръчва"
},
{
"category": "Доставчик – кашони",
"company": "Темподем",
"contact_person": "Панчо Шутилов",
"phone": "888/597557",
"email": "marketing_p.s@tempodem.com",
"scope": "кашони",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "поръчвали сме от малките кашони"
},
{
"category": "Доставчик – кашони",
"company": "Йови-СГ ЕООД",
"contact_person": "Георги Иванов",
"phone": "884271732",
"email": "office@yovi-sg.bg",
"scope": "кашони",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "оферти и за трите вида кашони + предоставени мостри 09.2024"
},
{
"category": "Доставчик – кашони",
"company": "Дунапак Родина",
"contact_person": "Милен Панайотов",
"phone": "882435370",
"email": "Milen.Panayotov@dunapack-packaging.com",
"scope": "кашони",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "оферти за всички кашони 12.2024"
},
{
"category": "Транспорт / логистика",
"company": "Разтранс ЕООД",
"contact_person": "Пенка Иванова - 0888426859 Светла Гълъбова - 0884583447",
"phone": "888/426859",
"email": "office@raztrans.bg",
"scope": "вътрешен транспорт",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "взимат пратки на Деламод/Юлоджистик,доставка на метали и др."
},
{
"category": "Транспорт / логистика",
"company": "Хепитранс ЕООД",
"contact_person": "Евгени - 0895558077 Петър Арабаджиев - 0893688080",
"phone": "",
"email": "office@happytrans.bg",
"scope": "вътрешен транспорт",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "вътрешни товари - метали и др."
},
{
"category": "Транспорт / логистика",
"company": "Тим Транс ЕООД",
"contact_person": "Владимир Велинов - +359 895 496 966",
"phone": "894/551606 - офис",
"email": "timtrans@abv.bg",
"scope": "вътрешен транспорт",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "вътрешни товари - метали и др."
},
{
"category": "Транспорт / логистика",
"company": "Интерлогистика",
"contact_person": "Христина 0886643332",
"phone": "032/966600",
"email": "plovdiv@interlogistica.bg",
"scope": "доставки пратки извън БГ",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Алог ООД",
"contact_person": "Александър Александров 0894/670577 Аделина Филипова 0897/978676",
"phone": "",
"email": "a_alexandrov@alog-bg.com, a_filipova@alog-bg.com",
"scope": "Унгария/Швейцария",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Алог може за всичко, но си имат служители отговарящи за отделните релации"
},
{
"category": "Транспорт / логистика",
"company": "Алог ООД",
"contact_person": "Ангел Илиев",
"phone": "+359 892 25 10 41",
"email": "a_iliev@alog-bg.com",
"scope": "Сърбия",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Алог ООД",
"contact_person": "Даниела Александрова",
"phone": "882/040576",
"email": "d_alexandrova@alog-bg.com",
"scope": "Вътрешен транспорт",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Алог ООД",
"contact_person": "Марио Иванов/ Калина Димитрова",
"phone": "0896 60 77 47/0897978789",
"email": "m_ivanov@alog-bg.com; k_dimitrova@alog-bg.com",
"scope": "Испания/ Португалия",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Алог ООД",
"contact_person": "",
"phone": "",
"email": "a_metodiev@alog-bg.com g_trifonov@alog-bg.com",
"scope": "Италия",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Анда",
"contact_person": "Йорданка Перпелиева",
"phone": "888/233443",
"email": "anda06.transport@gmail.com",
"scope": "Италия Монтебелуна + вс.от 20-ти код - Лисоне (Марко), Mondo, Brianza",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Деламод",
"contact_person": "Антония Токмакчиева/ Али Заимов - Франция и Литва",
"phone": "Антония - 0887 770582 Али 0882 034 769",
"email": "antonia.tokmakchieva@delamode-group.com ali.zaimov@delamode-group.com",
"scope": "Литва и Франция",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Деламод може за всичко, но си имат служители отговарящи за отделните релации"
},
{
"category": "Транспорт / логистика",
"company": "Деламод",
"contact_person": "Ралица Досева и Йоана Миланова",
"phone": "Ралица-0884 109739, Йоана-0884 099052,",
"email": "ralitsa.doseva@delamode-group.com yoana.milanova@delamode-group.com",
"scope": "Полша",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Деламод",
"contact_person": "Йордан Димов/ Павел Николов",
"phone": "088 777 05 53",
"email": "yordan.dimov@delamode-group.com; pavel.nikolov@delamode-group.com",
"scope": "Германия и Белгия",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Деламод",
"contact_person": "Лариса Аврамова",
"phone": "882064636",
"email": "larisa.avramova@delamode-group.com tihomir.nikolov@delamode-group.com",
"scope": "Италия",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Деламод",
"contact_person": "",
"phone": "882260778",
"email": "george.jeleapov@delamode-group.com",
"scope": "Унгария",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Юлоджистик",
"contact_person": "Тони Ганев",
"phone": "879/300038",
"email": "sales@ulogistics.eu",
"scope": "Италия (Матера), Белгия, Франция, Сърбия, Полша; вътрешни пратки",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Филанел",
"contact_person": "Галя",
"phone": "885/416766",
"email": "filanellogistik@gmail.com",
"scope": "Германия",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Алог ООД",
"contact_person": "Надя Петрова",
"phone": "0893 384 825",
"email": "n_petrova@alog-bg.com",
"scope": "Полша",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Юнайтед Фрейт",
"contact_person": "Радослав Спасов",
"phone": "894/452451",
"email": "spasov@unitedfreight.at",
"scope": "всичко",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Унилог",
"contact_person": "Валя",
"phone": "888/648975",
"email": "office@unilog-bg.com",
"scope": "всичко",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Некст Лоджистик",
"contact_person": "Найден Колев",
"phone": "895/544223",
"email": "nkolev@nextlogistic.eu",
"scope": "всичко",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "TRANSLAND Ltd.",
"contact_person": "Иво Иванов",
"phone": "887410056",
"email": "ivanov@transland.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Евробул",
"contact_person": "Велина Колева",
"phone": "888/115188",
"email": "koleva@evrobul.com",
"scope": "всичко",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "засега сме стигали само до оферти"
},
{
"category": "Транспорт / логистика",
"company": "Димекс Логистикс ЕООД.",
"contact_person": "",
"phone": "884/129735",
"email": "Ivan.Madjarov@dimexlog.bg",
"scope": "ТУРЦИЯ",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Каролина Ко ЕООД/Ая Експрес ООД",
"contact_person": "Гергана",
"phone": "885/777075",
"email": "gergana@karolina-co.com",
"scope": "всичко/ Германия/Белгия/ Холандия",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "DHL",
"contact_person": "Ивелин Братанов",
"phone": "+359 885 850 995",
"email": "ivelin.bratanov@dhl.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Транспорт / логистика",
"company": "Гопет Транс",
"contact_person": "Troyan Dosov",
"phone": "359889880331",
"email": "troyan.dosov@gopettrans.com",
"scope": "Германия / Гърция / Румъния / Словакия / Унгария / Полша / Чехия / Холандия / Белгия / Великобритания / Италия",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Али Есев Велинград",
"contact_person": "Али Есев",
"phone": "886/703802",
"email": "",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "взима на място / стокова"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Асен Карамитев-Смолян",
"contact_person": "",
"phone": "887/885561",
"email": "",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Белчеви Дизайн (Разлог)",
"contact_person": "Екатерина Белчева",
"phone": "898/849358",
"email": "katia_belcheva@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Еконт-офис Предела-Разлог; за тяхна сметка"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Би Фоам-98 ЕООД (Петрич)",
"contact_person": "Васил Филипов",
"phone": "879/336216",
"email": "Bfoam98@gmail.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "до адрес-гр.Петрич, ул.Ильо Войвода 50, транспорт за сметка на клиента,"
},
{
"category": "Клиент – вътрешен пазар",
"company": "БМД Биджеви",
"contact_person": "",
"phone": "",
"email": "pepi_bmd@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 1,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Братя Коцеви",
"contact_person": "Сийка Коцева",
"phone": "887/309978",
"email": "kocevi1@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "На място идват да вземат поръчките си"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Булмебел",
"contact_person": "Дора Цветкова",
"phone": "877/900226",
"email": "",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Валатанс",
"contact_person": "Вальо",
"phone": "887/777433",
"email": "valatans05@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "транспорт за наша сметка /Транспрес/- стокови"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Велея Хоум /Виденов/",
"contact_person": "Катя Димова",
"phone": "892/296807",
"email": "katia.dimova@videnov.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "транспрес"
},
{
"category": "Клиент – вътрешен пазар",
"company": "ВКФ Ренцел",
"contact_person": "Емилия Христова",
"phone": "896606733",
"email": "emig@vkf-renzel.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "те си организират транспорта; фактура само по мейла"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Готика дизайн",
"contact_person": "",
"phone": "879/111333",
"email": "",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Дедал-1995",
"contact_person": "",
"phone": "",
"email": "dedal_95@abv.bg, nedkovska@dedal95.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Детелина /Коцето/",
"contact_person": "",
"phone": "898/443888",
"email": "detelina1969@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "стокова"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Део Макс",
"contact_person": "Донка Динкова",
"phone": "",
"email": "donka_dinkova@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "фактура + на място си получават поръчката"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Джи Отто",
"contact_person": "Фабио",
"phone": "879/910820",
"email": "purchase.gi.otto@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "стокова/фактура/ взима на място"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Дона груп",
"contact_person": "Кремена",
"phone": "879/677952",
"email": "donagroup27@gmail.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "взима на място / стокова"
},
{
"category": "Клиент – вътрешен пазар",
"company": "ЕВРО ГЕЙМС ТЕХНОЛОДЖИ - ООД",
"contact_person": "Десислава Щетинска",
"phone": "359-876-590-3830 359-886-996-577 359-878-593-997 359-888-790-277 ---------------- 888/800589",
"email": "virginia.doncheva@egt.com; desislava.eftimova@egt.com; dobrin.zlatanov@egt.com; konstantin.petrov@egt.com; raina.nedyalkova@egt.com; desislava.shtetinska@egt.com;",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 1,
"notes": "взимат на място или изпращаме ние както се разберем. Стокова на лист + фактура по имейл, като във ф-рата да пише дата на падеж! За всяка заявка отделна фактура!"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Езакс - столове",
"contact_person": "Валерия Ризова",
"phone": "898/484745",
"email": "acc@ezax.bg, sales@ezax.bg; vr@ezax.bg; it@ezax.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 1,
"notes": "Еконт-гр.Троян офис Горското/Транспрес - (транспорт за наша сметка)"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Ем Ес Трейдинг",
"contact_person": "",
"phone": "889/910250",
"email": "sklad1@mstrading.bg, office@mstrading.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "транспорт за наша сметка /Транспрес/"
},
{
"category": "Клиент – вътрешен пазар",
"company": "ЕПИПЛО ДИЗАЙН - ЕООД",
"contact_person": "Златина",
"phone": "894359034",
"email": "epiplodizain@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "с техен транспорт; или транспорт за тяхна сметка"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Златен клас",
"contact_person": "",
"phone": "",
"email": "",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "взима на място / стокова"
},
{
"category": "Клиент – вътрешен пазар",
"company": "ЗММ Нова Загора",
"contact_person": "Свилен Сивов/Любомир Дачев",
"phone": "",
"email": "s.sivov@zmmnz.com,l.dachev@zmmnz.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "сами взимат поръчките на място/ фактура"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Интеркомплекс ООД",
"contact_person": "Георги Стойчев",
"phone": "",
"email": "gs.intercomplex@gmail.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Камбо ООД",
"contact_person": "Даниела Вълчева/ Яна Иванова",
"phone": "885/849680 / +359889511090",
"email": "office@kambo.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "с. Ябълково, общ. Димитровград, ул. Васил Левски 14"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Кедър 92",
"contact_person": "",
"phone": "886/131815",
"email": "",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Колорадо ЕТ",
"contact_person": "Ани Ангелова",
"phone": "",
"email": "ani.angelova@kolorado.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 1,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Контур",
"contact_person": "Елеонора Цветанова",
"phone": "884/108368",
"email": "eleonora@kontur-bulgaria.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Кофражна техника 95 АД",
"contact_person": "",
"phone": "",
"email": "m_garnevska@kofragna-bg.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 1,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Крос 1",
"contact_person": "Красимир Николов",
"phone": "",
"email": "cross_bg@yahoo.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "на място взимат"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Куалити",
"contact_person": "Капка Хайдутова",
"phone": "887/347724",
"email": "k.haidutova@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "транспрес за наша сметка/ имат отстъпка 5% добавя се към програмата"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Летиция Мебел",
"contact_person": "Илия Георгиев",
"phone": "888/711689",
"email": "leticia_mebel@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Офис на Еконт в град Монтана(Индустриална 30)"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Лумбреко ЕООД",
"contact_person": "Кристина Грудлева",
"phone": "876/330420",
"email": "info@lumbreco.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 1,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Марта-Атанас Димов (Наско - Пещера)",
"contact_person": "Наско",
"phone": "888/465111",
"email": "marta_divani@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "на място взима/ фактура"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Мая 09",
"contact_person": "Мая",
"phone": "887/274055",
"email": "",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "стокова/фактура"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Мебели Комфорт (Добрич)",
"contact_person": "Мима Андреева",
"phone": "897/842663",
"email": "",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "по Еконт за тяхна сметка- гр. Добрич, еконт Родина/ стокова"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Метма ООД",
"contact_person": "Милена Димитрова",
"phone": "884/624024",
"email": "metma@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 1,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "МИМ България АД",
"contact_person": "инж. Людмила Русанова",
"phone": "895/548142",
"email": "l.rusanova@mim.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Мита Стил",
"contact_person": "",
"phone": "",
"email": "rmi@vkf-renzel.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 1,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Мони 83",
"contact_person": "",
"phone": "",
"email": "office@moni83.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 1,
"notes": "фактура + на място си получават поръчката"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Начеви",
"contact_person": "Елица Пенева",
"phone": "879250237",
"email": "a.n.nachevi90@gmail.com,arch.jordan.nachev@gmail.com, office@nachevi.com supply@nachevi.com (nachevi@nachevi.com, nachevi90@abv.bg / счетоводство )",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Транспрес за наша сметка"
},
{
"category": "Клиент – вътрешен пазар",
"company": "НиБо 91-94 (Панко Балканджийски)",
"contact_person": "",
"phone": "898/594160",
"email": "nibo9194@gmail.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Транспрес за негова сметка"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Николети",
"contact_person": "Ради Кирова",
"phone": "887/500187",
"email": "radi.allebaufurnitures@gmail.com / nicoletti.sklad@gmail.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "транспрес"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Нордтон",
"contact_person": "",
"phone": "897/950368",
"email": "",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "взимат на място / стокова"
},
{
"category": "Клиент – вътрешен пазар",
"company": "ПАМИ 2 (Мебелиана ЕООД)",
"contact_person": "Пламен Маринов",
"phone": "896/820880",
"email": "pami2ood@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "На място идват за вземат поръчките си/ фактура"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Ретро Уют",
"contact_person": "Васил Димитров",
"phone": "359885560156",
"email": "123@aksaga.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Транспрес за наша сметка"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Роси ЕООД",
"contact_person": "Роза Анева",
"phone": "886/662200",
"email": "roza.aneva@rosi.bg, rosi@rosi.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "сами организират транспорта"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Соларити",
"contact_person": "",
"phone": "",
"email": "nangelieva@solaritybg.com / i.zaprianov@solaritybg.com/ k.kamburova@solaritybg.com - фактури",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 1,
"notes": "ние доставяме/ фактура"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Софалукс България ЕООД",
"contact_person": "Румен Янъков",
"phone": "887/383633",
"email": "sofalux@mail.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Софамакс/ вече Софамир от м.11.2025",
"contact_person": "",
"phone": "892/407966",
"email": "sofamax@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Солип",
"contact_person": "Таня",
"phone": "",
"email": "solip.office@gmail.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Станков ЕООД",
"contact_person": "Грета Станкова",
"phone": "897/844964",
"email": "stankov.furniture@gmail.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "плащат авансово; изпращаме по Еконт за тяхна сметка; Сандаснки, офис Стамболов"
},
{
"category": "Клиент – вътрешен пазар",
"company": "ТЕД",
"contact_person": "Зейнеб Русева",
"phone": "889929250",
"email": "zruseva@ted.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Стокова разписка със стоката и фактура по имейл /по договорка - основно ние доставяме"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Тедива",
"contact_person": "Галяна Тинкова",
"phone": "887/988923",
"email": "gtinkova@tediva.eu",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "техен транспорт/ за тяхна сметка с Транспрес"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Топ Мебел Груп",
"contact_person": "",
"phone": "887/313861",
"email": "dragodr@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Фолд Инс",
"contact_person": "",
"phone": "",
"email": "fold_ins@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Хомаг България",
"contact_person": "Бойко Стоянов; Даниела Рангелова",
"phone": "",
"email": "Boyko.Stoyanov.ext@homag.com, i.paskaleva@hgt-see.eu",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 1,
"notes": "Daniela.Rangelova.ext@homag.com"
},
{
"category": "Клиент – вътрешен пазар",
"company": "Шнайдер електрик България",
"contact_person": "",
"phone": "",
"email": "desislava.peneva@se.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 1,
"notes": ""
},
{
"category": "Клиент – вътрешен пазар",
"company": "Ямбол Комерс ООД",
"contact_person": "0879351131 - Станимир Стоев - организатор производство мебелна фабрика Нов Дом - Ямбол",
"phone": "",
"email": "yambolkomers@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Идват да си ги вземат със собствен транспорт, плащат авансово 100% преди взимане."
},
{
"category": "Клиент – външен пазар",
"company": "SAMAC /Matera/Montebelluna/Davide/Mariano/",
"contact_person": "Nicola, Francesco",
"phone": "",
"email": "nicola@samacitalia.it, francesco@samacitalia.it",
"scope": "",
"delivery_address": "31044 Montebelluna, Via della Madonnina 10/a, 75100 Matera, Italy, Via della comunicazione s.n. 22066 MARIANO COMENSE - CO, Italy, Via Boaresco 44",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар",
"company": "SAMAC Serbia",
"contact_person": "Kristina Lasica, Bojan Vasiljevic",
"phone": "",
"email": "samac@furhub.rs; sales@furhub.rs; nicola@samacitalia.it,",
"scope": "",
"delivery_address": "Beograd-Dobanovci , 11272, Branislava Nusica 24, Serbia, Kristina Lasica",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Митница(прилагаме фактури + декларация ЗПТ); фактурираме на SAMAC, доставяме до FurHub S doo"
},
{
"category": "Клиент – външен пазар",
"company": "GLM Sofa",
"contact_person": "Gianluca, Kriszta",
"phone": "",
"email": "gian.g@hotmail.it, glmsofa.kriszta@gmail.com",
"scope": "",
"delivery_address": "HU- 8444 Szentgal, HUNGARY, Petőfi utca 30, GLM SOFA KFT, Tel.: 00393481315991",
"invoice_email": "",
"no_price_increase": 0,
"notes": "транспортът е за тяхна сметка;"
},
{
"category": "Клиент – външен пазар",
"company": "GBF Sofa",
"contact_person": "Midanguas Stonys",
"phone": "",
"email": "mindaugas.stonys@gmail.com",
"scope": "",
"delivery_address": "LT 78366 Diauliai, Lithuania, Architektų g. 1",
"invoice_email": "",
"no_price_increase": 0,
"notes": "плащат преди товарене; транспорт за тяхна сметка"
},
{
"category": "Клиент – външен пазар",
"company": "Domino Sofa SPHK",
"contact_person": "Ventura Angelastri",
"phone": "",
"email": "venturaangelastri@yahoo.it",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар",
"company": "Italy Sofa Home SRL (Brianza Design)",
"contact_person": "",
"phone": "",
"email": "amministrazione@italysofahome.it",
"scope": "",
"delivery_address": "20030 SENAGO (MI), Italy, VIA BRUNO BUOZZI 5",
"invoice_email": "acquisto@brianzadesign.it, amministrazione@brianzadesign.it - тези имейли са на преходната им фирма Brianza Design",
"no_price_increase": 0,
"notes": "плащат 100 % авансово; транспорт за тяхна сметка"
},
{
"category": "Клиент – външен пазар",
"company": "Iza Mob",
"contact_person": "Iza Calarasi",
"phone": "",
"email": "izamob@yahoo.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "изпращаме за тяхна сметка до Еконт Силистра; EXW"
},
{
"category": "Клиент – външен пазар",
"company": "UAB Softline",
"contact_person": "Gintaras",
"phone": "",
"email": "gamyba@softlines.lt",
"scope": "",
"delivery_address": "LT-76160 Šiauliai, Lithuania, Basanaviciaus 69",
"invoice_email": "",
"no_price_increase": 0,
"notes": "транспорт за тяхна сметка; плащат при изпращане"
},
{
"category": "Клиент – външен пазар",
"company": "UAB Trivilita",
"contact_person": "Tadas Minkevicius",
"phone": "",
"email": "tadas.minkevicius@trivilita.lt",
"scope": "",
"delivery_address": "LT-76200 Šiauliai, Lithuania, Purienu str 51, UAB \"TRIVILITA\", Tel.: +370 618 36609",
"invoice_email": "",
"no_price_increase": 0,
"notes": "транспорт за тяхна сметка;"
},
{
"category": "Клиент – външен пазар",
"company": "AGI Lissone",
"contact_person": "Rosangela Bonanomi",
"phone": "",
"email": "r.bonanomi@agisrl.com, l.valtorta@agisrl.com",
"scope": "",
"delivery_address": "20851 Lissone (MB), VIA CORINO n 30 (interno 9), Italy",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар",
"company": "Verdu",
"contact_person": "Guillermo Puche",
"phone": "",
"email": "",
"scope": "",
"delivery_address": "Carretera de Villena km.1,5; 30510 Yecla (MURCIA), Spain",
"invoice_email": "",
"no_price_increase": 0,
"notes": "транспорт за тяхна сметка; отпечатваме специални етикети за кашоните"
},
{
"category": "Клиент – външен пазар",
"company": "Tip Toe",
"contact_person": "Brice Antoine/ Bastien Benoit",
"phone": "",
"email": "brice@tiptoe.fr/ bastien@tiptoe.fr",
"scope": "",
"delivery_address": "95670 MARLY LA VILLE, 6 RUE EUGENE POTTIER, QUAI 77, France, предварителна заявка най-малко 48 часа преди доставка на имейл claire@quai77.com/ peter@quai77.com (доставките са между 8 am and 12pm);",
"invoice_email": "delivery@tiptoe.odoo.com; vendor-bills@tiptoe.odoo.com",
"no_price_increase": 0,
"notes": "Изпращаме стоката само с проформа; Фактурата се праща по мейл"
},
{
"category": "Клиент – външен пазар",
"company": "Nicolas Greece",
"contact_person": "Nicolas Ragiadakos",
"phone": "",
"email": "nrag@dosragiadakos.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "когато сме готови с поръчка уточняваме транспорта с Наско 0888362844; клиентът си плаща"
},
{
"category": "Клиент – външен пазар",
"company": "Poltronissima SRL",
"contact_person": "",
"phone": "",
"email": "r.b.salotti@gmail.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар",
"company": "Belfort Belgium (Recor)",
"contact_person": "Rina Thijs",
"phone": "",
"email": "rina.thijs@recor-group.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар",
"company": "Aquinos Bedding Belgium",
"contact_person": "Johny Delvin",
"phone": "",
"email": "delvin.johny@aquinosgroup.com",
"scope": "",
"delivery_address": "9500 Geraardsbergen, Diebeke 20, Aquinos Bedding Belgium BV, Belgium",
"invoice_email": "AccountsPayableBE@aquinosgroup.com",
"no_price_increase": 0,
"notes": "Работно време на склада на клиента: Monday to Thursday from 7:30 a.m. to 11:45 a.m. ("
},
{
"category": "Клиент – външен пазар",
"company": "Aquinos Bedding Poland",
"contact_person": "Pawel Gliniak",
"phone": "",
"email": "Gliniak.Pawel@aquinosgroup.com",
"scope": "",
"delivery_address": "93-428 LODZ, Ul. Graniczna 60, Lodz, Poland, AQUINOS BEDDING POLAND Sp Z.o.o, tel: + 48426772034",
"invoice_email": "AccountspayablePL@aquinosgroup.com",
"no_price_increase": 0,
"notes": "EDI - потвърждаваме поръчките и преди изпращане генерираме специални етикети"
},
{
"category": "Клиент – външен пазар",
"company": "Aquinos Bedding Germany",
"contact_person": "Sandra Dietel",
"phone": "",
"email": "Dietel.Sandra@aquinosgroup.com",
"scope": "",
"delivery_address": "09518 Großrückerswalde, Germany, Streckewalder Straße 16, Aquinos Bedding Germany GmbH, 037343/80013",
"invoice_email": "AccountspayableDE@aquinosgroup.com",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар",
"company": "Aquinos Bedding Switzerland",
"contact_person": "Maitre Alain",
"phone": "",
"email": "Maitre.Alain@aquinosgroup.com",
"scope": "",
"delivery_address": "CH-4112 Fluh b/Basel, Switzerland, 601072, Custom Clearance 1556-0",
"invoice_email": "accountspayableCH@aquinosgroup.com",
"no_price_increase": 0,
"notes": "Митница(прилагаме фактури + декларация ЗПТ); При стойност на фактурата над 5000 евро, добавяме отстъпка (custom clearance) в размер на -50 евро"
},
{
"category": "Клиент – външен пазар",
"company": "BELGIAN BEDDING BV",
"contact_person": "Johny Delvin",
"phone": "",
"email": "johny.delvin@belgianbedding.be ; purchase@belgianbedding.be",
"scope": "",
"delivery_address": "9500 Geraardsbergen, Diebeke 20, BELGIAN Bedding BV, Belgium",
"invoice_email": "INVOICE@BELGIANBEDDING.BE",
"no_price_increase": 0,
"notes": "транспорт за наша сметка"
},
{
"category": "Клиент – външен пазар",
"company": "Cassina SPA",
"contact_person": "",
"phone": "",
"email": "Giuseppe.Breglia@cassina.it Matteo.Elli@cassina.it, fatturefornitori@cassina.it",
"scope": "",
"delivery_address": "20821 Meda, Italy IT, Via Luigi Busnelli 1",
"invoice_email": "",
"no_price_increase": 0,
"notes": "транспорт за тяхна сметка"
},
{
"category": "Клиент – външен пазар",
"company": "City Comfort SRL",
"contact_person": "",
"phone": "",
"email": "buyer.m@cityconfort.eu",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар",
"company": "SyForm / DML Harmony",
"contact_person": "Santiago Gasol",
"phone": "",
"email": "martial.muntz@harmony-group.fr, achat@harmony-group.fr",
"scope": "",
"delivery_address": "30100 Ales, 38 Avenue Vincent d'Indy, France",
"invoice_email": "",
"no_price_increase": 0,
"notes": "изпращаме най-често с TNT и Интерлогистика; транспорт за тяхна сметка"
},
{
"category": "Клиент – външен пазар",
"company": "Florenc Kubolli",
"contact_person": "",
"phone": "",
"email": "mobilerikubolli@gmail.com",
"scope": "",
"delivery_address": "Advese-Eenme, 9022 Divjake, Albania",
"invoice_email": "",
"no_price_increase": 0,
"notes": "EXW; сам си организира транспорта; плаща основно авансово (по договорка с Данко)"
},
{
"category": "Клиент – външен пазар",
"company": "MARASM SRL",
"contact_person": "Iza Calarasi",
"phone": "",
"email": "izamob@yahoo.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар",
"company": "Mondo",
"contact_person": "",
"phone": "",
"email": "",
"scope": "",
"delivery_address": "20825 BARLASSINA (MB), Italy, VIA GIOVANNI SEGANTINI 29",
"invoice_email": "",
"no_price_increase": 0,
"notes": "плащат 100% авансово (по проформа); транспорт за тяхна сметка"
},
{
"category": "Клиент – външен пазар",
"company": "Milling GmbH",
"contact_person": "Stefan Milling",
"phone": "",
"email": "st.milling@milling-bm.de",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар",
"company": "Novatus GmbH",
"contact_person": "Christian Schramm",
"phone": "",
"email": "christian.schramm@novatus-handel.de",
"scope": "",
"delivery_address": "96242, Sonnefeld, Germany, Am Roten Hügel 6",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар",
"company": "KROHNE Limited",
"contact_person": "Kevan Pack, Kevin Betts",
"phone": "",
"email": "K.Betts@KROHNE.com ; Kltd.centralisedpurchasing@krohne.com",
"scope": "",
"delivery_address": "Kevin Betts/Krohne Ltd,Riverside Business Park, Carousel Way 11,Northampton NN3 9HG,GB",
"invoice_email": "ukinvoices@krohne.com - invoice",
"no_price_increase": 0,
"notes": "за сега сме изпращали само мостри; ТНТ; Великобритания (извън ЕС)/30 дни от фактурата"
},
{
"category": "Клиент – външен пазар",
"company": "Pelfa Group",
"contact_person": "",
"phone": "",
"email": "fatture@pelfa.it",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар",
"company": "Bliss Ecospray",
"contact_person": "Francois Lelong",
"phone": "",
"email": "fx.lelong@bliss-ecospray.com",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар",
"company": "BEDDER B.V.",
"contact_person": "",
"phone": "",
"email": "info@bedder.nl",
"scope": "",
"delivery_address": "Steenstraat 2, 8375 HM Oldemarkt, The Netherlands",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Клиент – външен пазар (HOMAG)",
"company": "HOMAG GmbH",
"contact_person": "",
"phone": "",
"email": "Stefanie.Buehler@homag.com; Jasmin.Walz@homag.com",
"scope": "HOMAG Group (Германия)",
"delivery_address": "",
"invoice_email": "invoice-schopfloch@homag.com",
"no_price_increase": 0,
"notes": "Потвърждение на поръчки: SCM010@homag.com"
},
{
"category": "Клиент – външен пазар (HOMAG)",
"company": "HOMAG Bohrsysteme GmbH",
"contact_person": "",
"phone": "",
"email": "dorothee.kottenstette@homag.com; Patrick.Langer@homag.com",
"scope": "HOMAG Group (Германия)",
"delivery_address": "",
"invoice_email": "invoice-herzebrock@homag.com",
"no_price_increase": 0,
"notes": "Потвърждение на поръчки: einkauf-herzebrock@homag.com"
},
{
"category": "Клиент – външен пазар (HOMAG)",
"company": "Weinmann Holzbausystemtechnik GmbH",
"contact_person": "",
"phone": "",
"email": "Aleksandra.Wachowiak@durr.com",
"scope": "HOMAG Group (Германия)",
"delivery_address": "",
"invoice_email": "invoice@weinmann-partner.de Ingrid.Reutter@weinmann-partner.de",
"no_price_increase": 0,
"notes": "Потвърждение на поръчки: Aleksandra.Wachowiak@durr.com"
},
{
"category": "Клиент – външен пазар (HOMAG)",
"company": "HOMAG Automation GmbH",
"contact_person": "",
"phone": "",
"email": "Christian.Strassberger@homag.com",
"scope": "HOMAG Group (Германия)",
"delivery_address": "",
"invoice_email": "invoice-lichtenberg@homag.com",
"no_price_increase": 0,
"notes": "Потвърждение на поръчки: auftragsbestaetigungen-lichtenberg@homag.com"
},
{
"category": "Клиент – външен пазар (HOMAG)",
"company": "HOMAG Kantentechnik GmbH",
"contact_person": "",
"phone": "",
"email": "michelle.findeisen@homag.com Rene.Breitkreuz@homag.com",
"scope": "HOMAG Group (Германия)",
"delivery_address": "",
"invoice_email": "invoice-lemgo@homag.com",
"no_price_increase": 0,
"notes": "Потвърждение на поръчки: einkauf-lemgo@homag.com"
},
{
"category": "Клиент – външен пазар (HOMAG)",
"company": "HOMAG Plattenaufteiltechnik GmbH",
"contact_person": "",
"phone": "",
"email": "Armin.Roller@homag.com",
"scope": "HOMAG Group (Германия)",
"delivery_address": "",
"invoice_email": "invoice-holzbronn@homag.com",
"no_price_increase": 0,
"notes": "Потвърждение на поръчки: scm-ab-holzbronn@homag.com"
},
{
"category": "Доставчик – други",
"company": "Ostalbketten / YOKE (куки за колички)",
"contact_person": "",
"phone": "",
"email": "elena.kern@ostalbketten.de / промяна на имейл - info@yoke.eu",
"scope": "Куки за колички YOKE-LASTBOCK 2-056-25-1720",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Услуги / други",
"company": "Вода /Найс Уотър/",
"contact_person": "",
"phone": "0700 16 0 16",
"email": "",
"scope": "абонатен №:11259",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "регулярно минават вднъж седмично; оставят само ППП; около 20-то число изпращат фактурата по мейла; обслужват и Рогош"
},
{
"category": "Услуги / други",
"company": "Вендинг автомати",
"contact_person": "Васил",
"phone": "896/743552",
"email": "",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Услуги / други",
"company": "Сезалови чували /борса/",
"contact_person": "",
"phone": "896/296554",
"email": "",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Издават фактура допълнително, плаща се в брой"
},
{
"category": "Услуги / други",
"company": "Полиетил.пликове ( за обков)",
"contact_person": "Фолпак Груп ООД",
"phone": "888/605220",
"email": "",
"scope": "300/400мм",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "с фактура"
},
{
"category": "Услуги / други",
"company": "Пречиствателна станция",
"contact_person": "Тексо ЕООД",
"phone": "",
"email": "office@texo.bg",
"scope": "таблетки за пречиств.станция",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "вика се ВОМА периодично (ако се наложи)"
},
{
"category": "Услуги / други",
"company": "Еко Варна АД",
"contact_person": "Петьо - 0877373556 Антоанета - 0897863330",
"phone": "",
"email": "dakota_max@abv.bg",
"scope": "взимане на скраб Първенец / Рогош",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "С Петьо се уговаря транспорта, Антоанета изпраща кантарните бележки, на база на които се пускат фактури; не се начислява ДДС; фактурата се изпраща на посочения мейл и Управителят отива на място, за да разпише договор + придружаващи документи"
},
{
"category": "Услуги / други",
"company": "Уейстконсулт",
"contact_person": "Петя Николаева",
"phone": "894/622592",
"email": "p.nikolaeva@wasteconsult-bg.com",
"scope": "Отпадък информация",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "справка по имейл до 5-то число на месеца, за предходният месец (в копие Васка)"
},
{
"category": "Услуги / други",
"company": "Зара 11",
"contact_person": "Деляна Иванова",
"phone": "887/317511",
"email": "bgzara11@gmail.com",
"scope": "офис консумативи",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "заявки по телефон/вайбър"
},
{
"category": "Услуги / други",
"company": "Mитница",
"contact_person": "Чавдар Търновалийски",
"phone": "887/314738",
"email": "office@t2-consult.com",
"scope": "Т2 Консулт",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Услуги / други",
"company": "Счетоводство",
"contact_person": "Васка",
"phone": "878/797525",
"email": "vangelova@hermodbg.com",
"scope": "М-Софтсолюшънс",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Услуги / други",
"company": "К&К Mаркетинг\" EООД",
"contact_person": "",
"phone": "",
"email": "labels_plovdiv@kkmarketing.com",
"scope": "Етикети Таня принтер",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "(75/58/1/1000/25.4-0 цв/Thermal еко black mark)"
},
{
"category": "Услуги / други",
"company": "Камъни за тровал",
"contact_person": "",
"phone": "",
"email": "",
"scope": "Лена Агромашин",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Услуги / други",
"company": "Застраховки",
"contact_person": "Златка",
"phone": "",
"email": "z_georgieva@abakusbroker.com",
"scope": "Абакус",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Коли и трудова злополука; подаване на информация при напуснали и новоназначение служители"
},
{
"category": "Услуги / други",
"company": "Боя ХОМАГ",
"contact_person": "Rok Ajdnik, Felix Falke",
"phone": "",
"email": "f.falke@freilacke.de",
"scope": "Emil Frei GmbH & Co. KG",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Услуги / други",
"company": "СИМ Превент",
"contact_person": "инж. М. Линев",
"phone": "878103674",
"email": "simprevent@gmail.com",
"scope": "служба по трудова медицина",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Услуги / други",
"company": "Виртуал Сервиз",
"contact_person": "Добринка Пешева/ Вальо",
"phone": "0898 765 463; 0899 985 807",
"email": "office@turbomip.net",
"scope": "интернет",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "Интернет; Издават фактури за тримесечие"
},
{
"category": "Услуги / други",
"company": "МОВА 69 - ЕООД и ТАРА М6 - ЕООД",
"contact_person": "Светослав Козарев",
"phone": "879648755",
"email": "svetoslavkozarev56@gmail.com",
"scope": "Наемател Рогош (2*250 кв.м.)",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "В края на месеца на месеца издаваме фактура за наем 25-30 число(съгласувано с Данко); изпраща се по мейл + в копие е Данко"
},
{
"category": "Услуги / други",
"company": "Идънред",
"contact_person": "Надя Начева",
"phone": "893042427",
"email": "",
"scope": "ваучери",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "HR\\Договор ваучери - Идънред - Данко Системс\\Електронни ваучери"
},
{
"category": "Услуги / други",
"company": "Енерджи Стайл",
"contact_person": "Нели Ангелиева",
"phone": "885161580",
"email": "invoice@energystyle.bg + Данко и счетоводство в копие",
"scope": "продажба ел. енергия ФЕЦ",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": "получаваме по мейл от Данко протокол от Енерджи Стайл (посочени са MWh и цена) + протокол от ЕВН (за проверка на MWh); издаваме фактура от наша фирма Данко Системс ел. енергия (регистър 3) с последна дата на месеца, за който се отнася фактурата;"
},
{
"category": "Услуги / други",
"company": "ГЛОБЪЛ ЛИНКС - ЕООД",
"contact_person": "",
"phone": "",
"email": "krasimirpv73@gmail.com",
"scope": "Наемател Рогош от 10.2025г.",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
},
{
"category": "Услуги / други",
"company": "Трудова медицина",
"contact_person": "Валя Арабаджиева",
"phone": "887641336",
"email": "stm_bg2001@abv.bg",
"scope": "",
"delivery_address": "",
"invoice_email": "",
"no_price_increase": 0,
"notes": ""
}
];
